# Generated by Django 5.1.4 on 2026-09-05 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('listed', 'Listed'), ('price_change', 'Price change'), ('sold', 'Sold'), ('pending', 'Pending')], max_length=20, verbose_name='event')),
                ('price_lac', models.PositiveIntegerField(verbose_name='price (lac PKR)')),
                ('date', models.DateField(verbose_name='date')),
            ],
            options={
                'verbose_name': 'price history entry',
                'verbose_name_plural': 'price history',
                'db_table': 'price_history',
                'ordering': ['-date'],
            },
        ),
    ]
