# Generated by Django 5.1.4 on 2026-09-05 11:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('specialty', models.CharField(blank=True, max_length=150, verbose_name='specialty')),
                ('contact', models.CharField(blank=True, max_length=30, verbose_name='contact')),
                ('website', models.URLField(blank=True, verbose_name='website')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='latitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='longitude')),
            ],
            options={
                'verbose_name': 'hospital',
                'verbose_name_plural': 'hospitals',
                'db_table': 'hospitals',
                'ordering': ['name'],
            },
        ),
    ]
