FROM node:22-slim

ENV NEXT_TELEMETRY_DISABLED=1 \
    PORT=3000

RUN npm install -g pnpm

WORKDIR /app

COPY . .
RUN pnpm install --frozen-lockfile
RUN pnpm --filter web build

EXPOSE 3000

CMD ["pnpm", "--filter", "web", "start"]
