# Generated by Django 5.1.4 on 2026-09-05 10:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('type', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('high', 'High school'), ('college', 'College')], max_length=20, verbose_name='type')),
                ('grade_levels', models.CharField(blank=True, max_length=60, verbose_name='grade levels')),
                ('city', models.CharField(max_length=120, verbose_name='city')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='latitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='longitude')),
            ],
            options={
                'verbose_name': 'school',
                'verbose_name_plural': 'schools',
                'db_table': 'schools',
                'ordering': ['name'],
            },
        ),
    ]
