# Generated by Django 5.1.4 on 2026-09-05 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='website',
            field=models.URLField(blank=True, verbose_name='website'),
        ),
    ]
