# Generated by Django 5.1.4 on 2026-09-05 10:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brokerage', models.CharField(blank=True, max_length=150, verbose_name='brokerage')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='phone')),
                ('bio', models.TextField(blank=True, verbose_name='bio')),
                ('is_verified', models.BooleanField(default=False, verbose_name='verified')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
            ],
            options={
                'verbose_name': 'agent',
                'verbose_name_plural': 'agents',
                'db_table': 'agents',
                'ordering': ['-created_at'],
            },
        ),
    ]
