# Generated by Django 5.1.4 on 2026-09-05 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='year')),
                ('tax_paid_lac', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='tax paid (lac PKR)')),
                ('assessed_value_lac', models.PositiveIntegerField(blank=True, null=True, verbose_name='assessed value (lac PKR)')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_history', to='properties.property', verbose_name='property')),
            ],
            options={
                'verbose_name': 'tax history entry',
                'verbose_name_plural': 'tax history',
                'db_table': 'tax_history',
                'ordering': ['-year'],
                'constraints': [models.UniqueConstraint(fields=('property', 'year'), name='unique_tax_year_per_property')],
            },
        ),
    ]
