# Generated by Django 5.1.4 on 2026-09-05 10:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('neighborhoods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='image URL')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
            ],
            options={
                'verbose_name': 'property image',
                'verbose_name_plural': 'property images',
                'db_table': 'property_images',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('plot', 'Plot'), ('house', 'House'), ('apartment', 'Apartment'), ('villa', 'Villa')], max_length=20, verbose_name='property type')),
                ('status', models.CharField(choices=[('new', 'New'), ('open_house', 'Open house'), ('price_drop', 'Price drop'), ('for_sale', 'For sale'), ('sold', 'Sold')], default='for_sale', max_length=20, verbose_name='listing status')),
                ('address', models.CharField(max_length=255, verbose_name='address')),
                ('price_lac', models.PositiveIntegerField(verbose_name='price (lac PKR)')),
                ('plot_size', models.CharField(blank=True, max_length=60, verbose_name='plot size')),
                ('beds', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='beds')),
                ('baths', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='baths')),
                ('sqft', models.PositiveIntegerField(blank=True, null=True, verbose_name='covered area (sq ft)')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('cover_image_url', models.URLField(blank=True, verbose_name='cover image URL')),
                ('image_count', models.PositiveIntegerField(default=0, verbose_name='image count')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='agents.agent', verbose_name='agent')),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='neighborhoods.neighborhood', verbose_name='neighborhood')),
            ],
            options={
                'verbose_name': 'property',
                'verbose_name_plural': 'properties',
                'db_table': 'properties',
                'ordering': ['-created_at'],
            },
        ),
    ]
