# Generated by Django 5.1.4 on 2026-09-05 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Customer this listing is saved/favourited by, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_properties', to=settings.AUTH_USER_MODEL, verbose_name='saved by'),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property', verbose_name='property'),
        ),
    ]
