# Generated by Django 5.1.4 on 2026-09-05 10:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('city', models.CharField(max_length=120, verbose_name='city')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('median_price_lac', models.PositiveIntegerField(blank=True, null=True, verbose_name='median price (lac PKR)')),
                ('cover_image_url', models.URLField(blank=True, verbose_name='cover image URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
            ],
            options={
                'verbose_name': 'neighborhood',
                'verbose_name_plural': 'neighborhoods',
                'db_table': 'neighborhoods',
                'ordering': ['city', 'name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'city'), name='unique_neighborhood_per_city')],
            },
        ),
    ]
